name: Netlify

on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        uses: actions/setup-node@v1
      - run: yarn
      - run: ./node_modules/.bin/netlify deploy --build --dir=. --auth=${{ secrets.NETLIFY_TOKEN }}
        env:
          CI: true
